# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'lib/hu/common.rb'
    - 'lib/hu/telemetry.rb'

# Offense count: 14
Metrics/AbcSize:
  Max: 298

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 698

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 45

# Offense count: 16
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 254

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 43

# Offense count: 4
Style/ClassVars:
  Exclude:
    - 'lib/hu/deploy.rb'

# Offense count: 6
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/hu/cli.rb'
    - 'lib/hu/collab.rb'
    - 'lib/hu/common.rb'
    - 'lib/hu/deploy.rb'
    - 'lib/hu/telemetry.rb'

# Offense count: 3
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'lib/hu/cli.rb'
    - 'lib/hu/collab.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'lib/hu/deploy.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Enabled: false
