inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 1000

Metrics/AbcSize:
  Max: 500

Metrics/PerceivedComplexity:
  Max: 100


