# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'lib/hu/common.rb'
    - 'lib/hu/telemetry.rb'

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 450

# Offense count: 15
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 500

# Offense count: 4
Metrics/PerceivedComplexity:
  Max: 43

# Offense count: 4
Style/ClassVars:
  Exclude:
    - 'lib/hu/deploy.rb'

# Offense count: 6
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/hu/cli.rb'
    - 'lib/hu/collab.rb'
    - 'lib/hu/common.rb'
    - 'lib/hu/deploy.rb'
    - 'lib/hu/telemetry.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundClassBody:
  Exclude:
    - 'lib/hu/deploy.rb'

# Offense count: 3
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'lib/hu/collab.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Exclude:
    - 'lib/hu/deploy.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'lib/hu/deploy.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  Enabled: false
